language: ruby
rvm:
- 2.1.0
deploy:
  provider: heroku
  api_key:
    secure: xLXNOU5OOCnTPgpeCbTnCFukQrt5TmRB9t3Zld81x1Z7eryYOddP6uhS6F8wcZyzk1zInojtHH4QMNXHlKpdPvIbk/JdV0rdHwarXBz/ZnD2ofGbdc/5/1j/5zN1H1G7qIj3NBiqcQRsLMREzRGSlph9J5qRYYPUepCTiwUr6OU=
    app: vitorfox-rails-tutorial
