language: ruby
rvm:
- 2.1.0
deploy:
  provider: heroku
  api_key:
    secure: QX7FLxzEdAQfleZaPoc6oD1JO6fgvs4eDLhzXN+/fEPvFv9su4Bhm5IG4ewp024MRYBjN6N7ts/1dhcFsSw0HKK6HyTkI2HqbGhks3nlBbb+BWY8NPLy1BAbnRBc4vp4UdqCO7sP5kt8N1GAT2tYKM4VUDbq55Gzz80b+vFDx98=
