language: ruby
rvm:
- 2.1.0
deploy:
  provider: heroku
  api_key:
    secure: j6PnTHf1bEdIs5tnLKk6S0nl99UNhIaM+bqv/R6MEzPPSnQZh0wPBRHW/1A64hG7IGwtJDOQLnFEQ234af1P4oNDxayVzGJwu2YyEyqIG5Rwa/Lv2SAo8j4BBKCIokjXLjTeyOcW2PpQD1b5j1s1BuVrhOOfOOL5ULUaPMiHleE=
  app: vitorfox-rails-tutorial
  on:
    repo: vitorfox/rails_tutorial
